### ISSUE TITLE
Create function for multiGet

### ISSUE THREAD

**Issue by Tombert** [warrenfalk/rocksdb-sharp#10]
Thus far this library has been working great, but I'm curious if there are any plans on implementing a function do handle the `multiGet` functionality of RocksDB, as they have in the Java or Python versions.

**Comment by warrenfalk** [comment]
I'm implementing this today and will release today or tomorrow with support
for rocksdb 5.1.4.

**Comment by vsapronov** [comment]
@warrenfalk please let us know as soon as it's available

**Comment by warrenfalk** [comment]
This is released.  5.1.4 should be available on nuget and as a release.
