### ISSUE TITLE
API for listing all column families through C#

### ISSUE THREAD

**Issue by rapoth** [warrenfalk/rocksdb-sharp#11]
First of all, thank you for this wonderful binding! I am beginning to play around with it and so far it has been a breeze. 

As I see it currently, there is a _ListColumnFamilies_ call missing in the C# implementation compared to the [native implementation](https://github.com/facebook/rocksdb/blob/21d8c317966fb3ad0bae8cc03f16c505f2c0792f/include/rocksdb/db.h).

`DB::ListColumnFamilies(const DBOptions& db_options, const std::string& name, std::vector<std::string>* column_families)`

I see that you already added this call into the native wrapper [here](https://github.com/warrenfalk/rocksdb-sharp/blob/master/shared/Native.Wrap.cs#L67), but did not expose it in the [RocksDb C# class](https://github.com/warrenfalk/rocksdb-sharp/blob/368db05e2a4c19ce15dcba1705d5c19102098cd2/shared/RocksDb.cs).

Could you kindly update this when you get a chance? I am using v5.1.4 published on Nuget. Thank you!

**Comment by warrenfalk** [comment]
I can implement this function in the high level classes when I build for the new version.

**Comment by warrenfalk** [comment]
Implemented in 5.2.1
