### ISSUE TITLE
How to buildin rocksdb.dll in windows

### ISSUE THREAD

**Issue by eurake** [warrenfalk/rocksdb-sharp#13]
@warrenfalk 
You can give more infomation or steps how to build in windows.  Something like snappy 
1, Open "Developer command prompt for vs2015" 
2, Run git's bash.exe 
3, cd to the native-build folder within the repository
4, execute ./build-rocksdb.sh

**Comment by warrenfalk** [comment]
Those are still correct.  It should also work with VS 2017.  Don't forget the prerequisites also listed in the README.

The build-rocksdb.sh script is designed to grab a known-working version of rocksdb automatically, and also to download and build the source for snappy and gflags.  If you want to do something more advanced yourself, then I recommend reading the script to see what it's doing.

If you are having trouble at any particular stage in those instructions, let me know, and I might be able to clarify.
