### ISSUE TITLE
SST file Writer Class

### ISSUE THREAD

**Issue by hiral2cool** [warrenfalk/rocksdb-sharp#15]
I want a distributed computing and make one Generalized dictionary key value store so every body can access that db for that i can use the Concept of SST File Writer Class 
Every PC in distributed make own SST files and then Further all SST files are ingest into One DB 
Here is the links that i can accomplish my task
https://github.com/facebook/rocksdb/wiki/Creating-and-Ingesting-SST-files

is that class or API available in Rocksdb-Sharp 
or how can i accomplish this concept using Rocksdb C#

**Comment by warrenfalk** [comment]
This has not yet been implemented in the C# wrapper.  I will consider adding it in a future release, or a PR would be welcome.

See ```#region SstFile``` in ```Native.Raw.cs``` for more info.

**Comment by hiral2cool** [comment]
ok thank you

**Comment by warrenfalk** [comment]
This has been added.  It should be in the next release.
