### ISSUE TITLE
Assembly is not signed

### ISSUE THREAD

**Issue by mkosieradzki** [warrenfalk/rocksdb-sharp#22]
Adding strong name to the assembly makes it much easier to consume.

**Comment by danielcrabtree** [comment]
Libraries are not strong named by default as it causes problems on platforms that don't support binding redirects.

If you need a library to have a Strong Name, use [StrongNamer](https://github.com/dsplaisted/strongnamer) to add one.

**Comment by mkosieradzki** [comment]
Thanks @danielcrabtree , that's a very helpful tool.
