### ISSUE TITLE
[Question] Why not P/Invoke?

### ISSUE THREAD

**Issue by mkosieradzki** [warrenfalk/rocksdb-sharp#23]
Current implementation of native interop uses dynamically generated IL. While this approach should be quite efficient, there are some implications of dynamic IL making library impossible to use in some scenarios.

For example it cannot be used in some environments with prohibited dynamic code generation or AOT scenarios.

Also IL generation adds some bloat to the .NET Core applications.

Are there still any issues with DllImport performance that justify dynamically generated IL instead of old good P/Invoke?

**Comment by warrenfalk** [comment]
The short answer to this is that P/Invoke gives no control over loading of the native libraries, and this control was basically necessary for having build output be truly portable.  This and #24 therefore require the same discussion.  Since it's already started there, I'll close this one.
