### ISSUE TITLE
Stop static linking against VC Redist

### ISSUE THREAD

**Issue by warrenfalk** [warrenfalk/rocksdb-sharp#26]
Static linking against VC allows for a zero-config deployment, but has drawbacks.

Copying this from note by  @mkosieradzki on issue #24.

>What are the reasons not to link statically against vcredist:
>1. Often RocksDB isn't the only one native library inside entire application. If all libraries were linked statically it would basically mean a lot duplication and memory waste inside a single application.
>2. VCredists are serviceable - it means they are subject to security updates.
>3. It decreases the ability to reuse memory image of vcredists between different applications as well.
>
>IMO it would be a good idea to stop static linking. If one wants zero-config deployment they can add nuget package with vcredist DLLs (again if we have switched to P/Invoke it will work out-of-the-box).
>
>I know it's controversial and I've seen you have put some effort into static linking however I think it's worth the consideration. Even project that huge like dotnet Core requires VCRedist. (Maybe it's a good idea to link against the same VCRedist version required by the .NET Core already? :)

Static linking was added by @wangjia184, so I'd like to make sure he's able to weigh in.

I'm most concerned about the second drawback given above.  Increasing the surface for attack vectors is not something I had previously considered.

**Comment by wangjia184** [comment]
For the reason 1 & 3, actually they are the same,  statically linking the runtime increases the memory for several megabytes,  Perhaps ten years ago someone may be afraid of that, nowadays I don't think that is an issue.

For the reason 2,  indeed it includes the responsibility for the one who  compiles the binaries to upgrade the VCRedist to latest version.

There is no perfect answer. Some one prefer static linking when others like dynamic.   My suggestion is to have two different NuGet packages to release the native binaries, one for dynamic and the other with statically linking, Then it is the user's choice.

Personally I choose statically linking is because my app is deployed in docker container which basing on the windowsservercore docker image.  With statically linked binaries,  the only required operation is to COPY the files when building the docker image.

**Comment by mkosieradzki** [comment]
ad 1 and 3: I would say exactly opposite: many years ago when applications were monolithic it made no difference. Today micro-services are the dominant architecture and even .NET Core is designed in a more modular manner (so only truly required modules are loaded into memory).

One of the expected usages for RocksDB is database-per-tenant (service-per-tenant). In such architecture static linking means a lot wasted memory.

BTW. why don't you just copy the redist dlls to the application folder as well? You don't need static linking for that.

BTW2. If you use docker then it is even easier. Even basic examples from Microsoft show how easy it is to add vcredist to docker... https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/optimize-windows-dockerfile

**Comment by warrenfalk** [comment]
All things being equal, my preference would be to leave the bundled binary as it is configured in the rocksdb repo.

But since all things are not equal, my guiding principle is that zero configuration wins as long as that which it displaces can still reasonably be achieved another way.  Therefore insofar as non-static linking both 1) places hurdles in the way of entry and 2) can be achieved another way, it will be avoided.

Unfortunately, I believe that both 1 and 2 are true.  As long as deployment of the code will routinely land it where there is by default no compatible VCRedist, then 1 is true.  As long as you can override this behavior by using your own version of the rocksdb binary (for example by installing it to a the library search path on that machine) then 2 is true.

Also much of the argument from memory doesn't make sense to me.  The rocksdb library itself is quite large.  Any user copying dependent libraries, including rocksdb, to the application folder of every application is already tacitly admitting that space efficiency is not his goal.  If it were, he would use a shared installation strategy, and if he is managing a shared installation strategy then he can use a version of the rocksdb binary that is not statically linked.

Note that this is why RocksDbNative and RocksDbSharp are separate packages.  It is so that you can install RocksDbSharp alone and manage the native binary yourself if you want.  We could create a non-static version of RocksDbNative, but again, why?  If you are getting your binaries by NuGet, you are publishing them to the application folder and duplicating the whole rocksdb binary - static linking is the least of your concerns.

**Comment by mkosieradzki** [comment]
After longer thought - I definitely agree with the point that rocksdb is sufficiently large and significant library that it deserves static linking. So the only real concern is the potential security risk. But I don't believe it's that much important so I am also for static linking which can be mitigated by releasing new version of rocksdb.
