### ISSUE TITLE
RocksDb.ListColumnFamilies returns garbage characters on Linux

### ISSUE THREAD

**Issue by varunpuranik** [warrenfalk/rocksdb-sharp#32]
ListColumnFamilies seems to return incorrect strings on Linux. For example, I updated the ColumnFamilyExample and updated it to ListColumnFamilies and printed them, and here is what I get - "PJ  ,L".
So I am not able to use the list of returned Column families and do a GetColumnFamily on them. 
This seems to work fine on Windows.

**Comment by jekakmail** [comment]
Also Win 7 x64 sp1. Win 10 x64 - correctly

**Comment by warrenfalk** [comment]
Merged PR, thanks @jekakmail !
