### ISSUE TITLE
Remove does not work when using ColumnFamilies

### ISSUE THREAD

**Issue by varunpuranik** [warrenfalk/rocksdb-sharp#35]
The following API does not work - 
public void Remove(byte[] key, ColumnFamilyHandle cf = null, WriteOptions writeOptions = null)

It seems like it takes in the ColumnFamilyHandle but does not use it in the remove, causing the remove to fail.

**Comment by themucha** [comment]
I've submitted a PR that fixes this: https://github.com/warrenfalk/rocksdb-sharp/pull/31

**Comment by warrenfalk** [comment]
PR merged, thanks @themucha
