### ISSUE TITLE
Is block cache supported?

### ISSUE THREAD

**Issue by ghost** [warrenfalk/rocksdb-sharp#38]
Is setting block cache supported?

https://github.com/facebook/rocksdb/wiki/Block-Cache

I can't find anywhere to make a NewLRUCache call.

**Comment by warrenfalk** [comment]
The following is possible in the most recent version in master:

```c#
new DbOptions().SetBlockBasedTableFactory(new BlockBasedTableOptions().SetBlockCache(Cache.CreateLru(1024 * 1024)))
```
