### ISSUE TITLE
Instantiating SstFileWriter causes a memory allocation exception

### ISSUE THREAD

**Issue by vadim-berman** [warrenfalk/rocksdb-sharp#40]
`SstFileWriter sfw = new SstFileWriter();`

crashes the system, regardless of whether it's made before a call to `DB.Open` or after.

**Comment by saikatguha** [comment]
@vadim-berman Were you able to resolve or find a work-around?

**Comment by vadim-berman** [comment]
I think I just dropped this thing altogether. But then, it was over half a year ago, I simply don't remember.

**Comment by saikatguha** [comment]
For anyone else running into this, explicitly passing in the `ioOptions` argument to the constructor avoids the memory access issue.
`SstFileWriter sfw = new SstFileWriter(new EnvOptions(), new ColumnFamilyOptions());`

**Comment by warrenfalk** [comment]
fixed in master as of e90fa1a97e3a55d118d356e20b6734087f1d2ee1
