### ISSUE TITLE
ArgumentNullException in Get(byte[], byte[]) when key does not exist

### ISSUE THREAD

**Issue by RealDolos** [warrenfalk/rocksdb-sharp#44]
When calling `public long Get(byte[] key, long keyLength, byte[] buffer, long offset, long length, ColumnFamilyHandle cf = null, ReadOptions readOptions = null)` or the other `Get()`s which redirect there, the code in https://github.com/warrenfalk/rocksdb-sharp/blob/8818ab4e7917877a99f6f1b25791bc1f29679a9a/RocksDbSharp/RocksDb.cs#L111-L121 tries to unconditionally copy the from the result ptr. That pointer might be a nullptr, however, if the key is not found, in which case the `Marshall.Copy` throws an `ArgumentNullException`.

Instead, the method should either throw a more appropriate exception, or return a proper result code.
Just returning `0` would be wrong, as you cannot distinguish that from a an empty/null db value, so returning something less than `0` might work better.

**Comment by warrenfalk** [comment]
Fixed
