### ISSUE TITLE
Undetectable truncation in Get(byte[], byte[]) when key does not exist

### ISSUE THREAD

**Issue by RealDolos** [warrenfalk/rocksdb-sharp#45]
https://github.com/warrenfalk/rocksdb-sharp/blob/8818ab4e7917877a99f6f1b25791bc1f29679a9a/RocksDbSharp/RocksDb.cs#L111-L121

The code will truncate the value if the passed in buffer is not big enough. Furthermore, since it returns `valLength` which is reassigned to `Min(length, valLength)`, this truncation cannot be detected.

In my opinion, the best way to address this would be to return the actual db length. This allows users to get a truncated result while they can easily check if a truncation occurred by checking if the method result (valLength) is bigger than the length they passed in.

**Comment by warrenfalk** [comment]
Fixed
