### ISSUE TITLE
Add prefix_same_as_start to ReadOptions

### ISSUE THREAD

**Issue by Peska** [warrenfalk/rocksdb-sharp#49]
I wonder if you could add prefix_same_as_start:

https://github.com/facebook/rocksdb/blob/64324e329eb0a9b4e77241a425a1615ff524c7f1/include/rocksdb/options.h#L1086

to ReadOptions in this library. It was added to RocksDb api after your last update.

**Comment by warrenfalk** [comment]
this option was added to master and should be released in version 5.18.3 soon
