### ISSUE TITLE
Question: how do I prevent LOG.old.XXXX to grow out of control

### ISSUE THREAD

**Issue by AndreSteenbergen** [warrenfalk/rocksdb-sharp#55]
I use RocksDb.OpenReadOnly(options, config.GetString("akka.rocksdb.path"), false); Every 10 seconds or so. This way I keep a few recent readers present at all time. Problem is I end up with quite a lot of log.OLD files.

How do I keep my directory somewhat clean?

**Comment by warrenfalk** [comment]
That's a question about rocksdb internal behavior that I don't know enough about to answer.  The question probably should be posed to the rocksdb team, but they may expect you to translate to the C++ equivalent.  You might try looking at this: https://github.com/facebook/rocksdb/issues/2166 which suggests that there is a ```delete_obsolete_files_period_micros option```.  You might try ```DbOptions.SetDeleteObsoleteFilesPeriodMicros()```, but I can't speak much to its behavior other than the summary included which is:
```c#
        /// <summary>
        /// The periodicity when obsolete files get deleted. The default
        /// value is 6 hours. The files that get out of scope by compaction
        /// process will still get automatically delete on every compaction,
        /// regardless of this setting
        /// </summary>
```
