### ISSUE TITLE
TTL support

### ISSUE THREAD

**Issue by Borlay** [warrenfalk/rocksdb-sharp#57]
Is there a way to set TTL? I found TTL option for WAL, but i think it's not the same as this:
https://github.com/facebook/rocksdb/wiki/Time-to-Live 

Do you have plans to add it?

**Comment by warrenfalk** [comment]
You are correct, the WAL option is different.  I've added OpenWithTtl() to the RocksDb class on master, and this should be released with 5.18.3 which I expect to release soon.
