### ISSUE TITLE
Contact request

### ISSUE THREAD

**Issue by tkstanczak** [warrenfalk/rocksdb-sharp#59]
Hi Warren,

Please forgive me this way of reaching out to you, but I could not find any contact details online.
We would greatly benefit from hiring you to do a few days of consulting to help with the way we use RocksDB / rocksdb sharp in our project (https://github.com/NethermindEth/nethermind).

Please let me know if that is something that you could potentially be interested in.
tkstanczak@nethermind.io

Best Regards,
Tomasz

**Comment by warrenfalk** [comment]
No problem.  My email is warren@warrenfalk.com

**Comment by tkstanczak** [comment]
Thanks, sent you an e-mail.
