### ISSUE TITLE
snapshots

### ISSUE THREAD

**Issue by ren85** [warrenfalk/rocksdb-sharp#6]
It seems there is no support for snapshots in the current release. Is this due to some problems or simply just not done yet?

**Comment by ren85** [comment]
Nevermind, it was easy to add them https://github.com/ren85/rocksdb-sharp

**Comment by chester89** [comment]
Can you make a PR?

**Comment by warrenfalk** [comment]
I've added snapshots to master using ren85's commit, plus some refactoring to conform to conventions.  In particular, I renamed SnapShot to Snapshot.
