### ISSUE TITLE
Support .net core with nuget

### ISSUE THREAD

**Issue by paramr** [warrenfalk/rocksdb-sharp#7]
Tried to use RocksDbSharp with .net core.  Does not work.

error: Package RocksDbSharp 4.13.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package RocksDbSharp 4.13.1 supports: net40 (.NETFramework,Version=v4.0)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
log  : Lock file has not changed. Skipping lock file write. Path: /home/param/tensorX/project.lock.json
log  : project.json
log  : Restore failed in 3009ms.

Errors in project.json
    Package RocksDbSharp 4.13.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package RocksDbSharp 4.13.1 supports: net40 (.NETFramework,Version=v4.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

**Comment by paramr** [comment]
Quite a few changes in reflection emit in .net core makes this non trivial.  https://github.com/dotnet/coreclr/issues/2222

project.json that I was trying with:
{
  "name": "RocksDbSharp",
  "version": "4.13.1",
  "buildOptions": {
    "allowUnsafe": true,
    "debugType": "portable",
    "define": [
      "RACE", "ROCKSDB_DB_OPERATIONS", "ROCKSDB_OPTIONS",
      "ROCKSDB_WRITE_OPTIONS", "ROCKSDB_READ_OPTIONS",
      "ROCKSDB_WRITE_BATCH", "ROCKSDB_BLOCK_BASED_TABLE_OPTIONS",
      "ROCKSDB_FILTER_POLICY", "ROCKSDB_SLICETRANSFORM", "ROCKSDB_ITERATOR"
    ],
    "compile": {
      "exclude": [ "**" ],
      "includeFiles": [
        "BinaryComparer.cs",
        "ColumnFamilies.cs",
        "ColumnFamilyHandle.cs",
        "ColumnFamilyOptions.cs",
        "DbOptions.cs",
        "Iterator.cs",
        "Native.Wrap.cs",
        "Native.Raw.cs",
        "Native.Load.cs",
        "Native.Marshaled.cs",
        "Options.cs",
        "Platform.cs",
        "Properties/AssemblyInfo.cs",
        "ReadOptions.cs",
        "RocksDb.cs",
        "RocksDbSharpException.cs",
        "RocksDbException.cs",
        "Snapshot.cs",
        "WriteBatch.cs",
        "WriteOptions.cs",
        "BlockBasedTableOptions.cs",
        "BloomFilterPolicy.cs",
        "SliceTransform.cs",
        "AutoNativeImport.cs"
      ]
    }
  },
  "dependencies": {
    "RocksDbNative": "4.13.4"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        },
        "System.Runtime.Serialization.Formatters": "4.3.0",
        "System.Reflection.Emit": "4.3.0"
      }
    }
  }
}

**Comment by warrenfalk** [comment]
The reflection changes do not seem to be a problem.  Everything that the library needs was available in existing .net core packages.  However, some tweaking was necessary to use new APIs.

I was able to get this to work except for the native binaries.  If you can figure out how you should include native binaries in a nuget package for .net core, feel free to give it a shot.  I had tried to keep these separate so that you can install the managed library without installing the native libraries for every platform, but the way the new .net core stuff is designed, this might be possible.
