### ISSUE TITLE
Open database as read-only

### ISSUE THREAD

**Issue by danfarino** [warrenfalk/rocksdb-sharp#9]
Great project! I'm so glad I found it.

Any plans to add the ability to open a database as read-only?

**Comment by warrenfalk** [comment]
Added OpenReadOnly() method to wf/readonly branch.  I'll finish testing and publish a nuget update soon.

**Comment by warrenfalk** [comment]
Nuget is updated

**Comment by danfarino** [comment]
thanks a lot man!
